mysite/board/urls.py
from . import views
from django.urls import path, include

app_name = 'board'
urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path('<int:pk>/', views.Detail.as_view(), name='detail'),
    path('companymanager/', views.Companymanager.as_view(), name='companymanager'),
    path('updatecompany/<int:pk>/', views.UpdateCompany.as_view(), name='updatecompany'),
    path('deletecompany/<int:pk>/', views.DeleteCompany.as_view(), name='deletecompany'),
    path('<int:pk>/deletecompany', views.DeleteCompany.as_view(), name='deletecompany'),
    path('<int:pk>/updateproject', views.updateproject, name='updateproject'),
    path('<int:pk>/updatecomment', views.updatecomment, name='updatecomment'),
    path('<int:pk>/updatecompany', views.UpdateCompany.as_view(), name='updatecompany'),
    path('<int:pk>/deleteproject', views.deleteproject, name='deleteproject'),
    path('<int:pk>/deletecomment', views.deletecomment, name='deletecomment'),
    path('<int:pk>/detailproject', views.DetailProject.as_view(), name='detailproject'),
    path('login', views.Login.as_view(), name='login'),
    path('register', views.Register.as_view(), name='register'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('cabinet/<int:pk>/', views.Cabinet.as_view(), name='cabinet'),
    path('updatecabinet/<int:pk>', views.UpdateCabinet.as_view(), name='updatecabinet'),
    path('comment', views.Comment.as_view(), name='comment'),
    ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('board.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

mysite/board/models.py
from django.db import models
from phone_field import PhoneField
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
Account = get_user_model()


class Company(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name="Автор", null=True,
        blank=True)

    name = models.CharField(
        max_length=20,
        db_index=True,
        verbose_name="Название компании")


    fio = models.CharField(
        max_length=50,
        db_index=True,
        verbose_name="ФИО директора")
    content = models.TextField(
        null=True,
        blank=True,
        verbose_name="Описание компании")
    published = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name="Дата публикации")
    done = models.DateTimeField(
        auto_now_add=False,
        db_index=True,
        verbose_name="Дата")
    adress = models.CharField(
        max_length=50,
        db_index=True,
        verbose_name="Адрес")
    phone = PhoneField(
        null=True,
        blank=True,
        verbose_name="Телефон")
    email = models.EmailField(
        null=True,
        blank=True,
        verbose_name="Почта")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural='Компании'
        verbose_name = 'Компания'
        ordering = ['-published']

class Project(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор", null=True,
                               blank=True)
    company = models.ForeignKey(
        'Company',
        null=True,
        on_delete=models.PROTECT,
        verbose_name='Компания')

    title = models.CharField(
        max_length=20,
        db_index=True,
        verbose_name="Название проекта")


    content = models.TextField(
        null=True,
        blank=True,
        verbose_name="Описание проекта")
    date1 = models.DateTimeField(
        auto_now_add=False,
        db_index=True,
        verbose_name="Дата начала")
    date2 = models.DateTimeField(
        auto_now_add=False,
        db_index=True,
        verbose_name="Дата завершения")
    price = models.FloatField(
        null=True,
        blank=True,
        verbose_name="Цена")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural='Проекты'
        verbose_name = 'Проект'
        ordering = ['-date1']

class CompanyComment(models.Model):
    company = models.ForeignKey(
        'Company',
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Компания')


    project = models.ForeignKey(
        'Project',
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Проект')


    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор комментария", null=True,
                               blank=True)

    manager = models.CharField(
        max_length=50,
        db_index=True,
        verbose_name="Менеджер"
    )
    text = models.TextField(
        null=True,
        blank=True,
        verbose_name="Описание")
    CHOICES = (
        ("Заявка", "Заявка"),
        ("Письмо", "Письмо"),
        ("Сайт", "Сайт"),
        ("Входящее письмо", "Входящее письмо"),
        ("Инициатива компании", "Инициатива компании"),
    )
    chanel = models.CharField(max_length=300, choices=CHOICES, verbose_name="Канал общения" )
    CHOICE = (
        ("Like", "Like"),
        ("Dislike", "Dislike"),
    )
    ergebnis = models.CharField(max_length=300, choices=CHOICE, verbose_name="Оценка")
    status = models.BooleanField(verbose_name="Статус", default=False)
    class Meta:
        verbose_name_plural='Комментарии'
        verbose_name = 'Комментарий'
        ordering = ['-company']




        

mysite/board/forms.py
from django.forms import ModelForm, Textarea
from .models import Company, Project, CompanyComment
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

class CompanyForm(ModelForm):
    class Meta:
        model= Company
        fields = ('name', 'fio', 'content', 'done', 'adress', 'phone', 'email' )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'
class ProjectForm(ModelForm):
    class Meta:
        model= Project
        fields = ('title', 'content', 'date1', 'date2', 'price' )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'
class AuthForm(AuthenticationForm, ModelForm):
    class Meta:
        model= User
        fields = ('username', 'password')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'

class RegisterForm(ModelForm):
    class Meta:
        model= User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class RegisterFormm(ModelForm):
    class Meta:
        model= User
        fields = ('first_name', 'last_name', 'username', 'email')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'
    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user


class CommentForm(ModelForm):
    class Meta:
        model= CompanyComment
        fields = ('manager', 'text', 'chanel', 'ergebnis')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class']='form-control'

mysite/board/views.py
from django.shortcuts import render, redirect
from .forms import CompanyForm, ProjectForm, AuthForm,  CommentForm, RegisterForm, RegisterFormm
from django.urls import reverse, reverse_lazy
from .models import Company, Project, CompanyComment
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from .filters import ProjectFilter, CommentFilter
from django.core.paginator import Paginator


class IndexListView(ListView):
    model = Company
    template_name = 'board/index.html'
    context_object_name = 'bbs'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        filter = ProjectFilter(self.request.GET, queryset=Company.objects.all())
        paginated = Paginator(filter.qs, 2)
        page = self.request.GET.get('page')
        page_obj = paginated.get_page(page)
        context['filter'] = filter
        context['page_obj'] = page_obj
        return context

class Detail(FormMixin, DetailView):
    template_name = 'board/detail.html'
    model = Company
    form_class = ProjectForm
    second_form_class = CommentForm

    def get_success_url(self, **kwargs):
        pk = self.kwargs['pk']
        return reverse_lazy('board:detail', kwargs={'pk': pk})
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()
        context['current_project'] = Project.objects.filter(company = self.kwargs['pk'])
        context['current_comment'] = CompanyComment.objects.filter(company=self.kwargs['pk'])
        return context
    def post(self, request, *args, **kwargs):
        self.object = self.get_object( )
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'
            self.mess_type = False

        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.company=self.get_object()
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class Companymanager(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('board:login')
    model = Company
    template_name = 'board/companymanager.html'
    form_class = CompanyForm
    success_url = reverse_lazy('board:companymanager')
    def get_context_data(self, **kwargs):
        kwargs['bbs'] = Company.objects.order_by('-published')
        return super().get_context_data(**kwargs)
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author=self.request.user
        self.object.save()
        return super().form_valid(form)


class UpdateCompany(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('board:login')
    model = Company
    template_name = 'board/companymanager.html'
    form_class = CompanyForm
    def get_success_url(self, **kwargs):
        pk = self.kwargs['pk']
        return reverse_lazy('board:detail', kwargs={'pk': pk})
    def get_context_data(self, **kwargs):
        kwargs['update'] = True,
        kwargs['bbs'] = Company.objects.order_by('-published')
        return super().get_context_data(**kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.user != kwargs['instance'].author and self.request.user.id!=1:
            return self.handle_no_permission()
        return kwargs


class DeleteCompany(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('board:login')
    model = Company
    template_name = 'board/companymanager.html'
    success_url = reverse_lazy('board:index')
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != self.request.user and self.request.user.is_superuser == False and self.request.user.is_staff == False:
            return self.handle_no_permission()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)

def deleteproject(request, pk):
    get_project = Project.objects.get(id=pk)
    get_project.delete()
    return redirect(reverse('board:index'))

def deletecomment(request, pk):
    get_comment = CompanyComment.objects.get(id=pk)
    get_comment.delete()
    return redirect(reverse('board:index'))

def updatecomment(request, pk):
    success_update = False
    get_comment = CompanyComment.objects.get(id=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=get_comment)
        if form.is_valid():
            form.save()
            success_update = True
    template = 'board/detailproject.html'
    context = {'get_project': get_comment,
               'update': True,
               'bbs': Company.objects.order_by('-published'),
               'form': CommentForm(instance=get_comment),
               'success_update': success_update

               }
    return render(request, template, context)

def updateproject(request, pk):
    success_update = False
    get_project = Project.objects.get(pk=pk)

    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=get_project)
        if form.is_valid():
            form.save()
            success_update = True
    template = 'board/detail.html'
    context = {'get_project': get_project,
               'update': True,
               'bbs': Company.objects.order_by('-published'),
               'form': ProjectForm(instance=get_project),
               'success_update': success_update

               }
    return render(request, template, context)

class Login(LoginView):
    template_name = 'board/authorisation.html'
    form_class =AuthForm
    success_url = reverse_lazy('board:index')

    def get_context_data(self, **kwargs):
        kwargs['bbs'] = Company.objects.order_by('-published')
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return self.success_url

class Register(CreateView):
    model = User
    template_name = 'board/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('board:index')
    success_msg = 'Пользователь создан'

    def get_context_data(self, **kwargs):
        kwargs['bbs'] = Company.objects.order_by('-published')
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        form_valid = super().form_valid(form)
        username =  form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        auth_user = authenticate(username=username, password=password)
        login(self.request, auth_user)
        return form_valid

class Logout(LogoutView):
    next_page = reverse_lazy('board:login')

class Cabinet(ListView):
    model = User
    template_name = 'board/cabinet.html'
    context_object_name = 'bbs'
    def get_context_data(self, **kwargs):
        kwargs['profile'] = User.objects.get(id=self.request.user.id)
        return super().get_context_data(**kwargs)


class Comment(ListView):
    model = CompanyComment
    template_name = 'board/comment.html'
    context_object_name = 'bbs'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        filter = CommentFilter(self.request.GET, queryset=CompanyComment.objects.all())
        context['filter'] = filter
        paginated = Paginator(filter.qs, 2)
        page = self.request.GET.get('page')
        page_obj = paginated.get_page(page)
        context['filter'] = filter
        context['page_obj'] = page_obj
        return context

class UpdateCabinet(UpdateView):
    model = User
    template_name = 'board/cabinet.html'
    form_class = RegisterFormm
    success_url = reverse_lazy('board:index')
    def get_context_data(self, **kwargs):
        kwargs['update'] = True,
        kwargs['profile'] = User.objects.get(pk=self.kwargs['pk'])
        return super().get_context_data(**kwargs)

class DetailProject(CreateView):
    model = Project
    template_name = 'board/detailproject.html'
    form_class = CommentForm
    def get_success_url(self, **kwargs):
        pk = self.kwargs['pk']
        return reverse_lazy('board:detailproject', kwargs={'pk': pk})
    def get_context_data(self, **kwargs):
        kwargs['project'] = Project.objects.get(pk=self.kwargs['pk'])
        kwargs['current_comment'] = CompanyComment.objects.filter(project=self.kwargs['pk'])
        return super().get_context_data(**kwargs)
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author=self.request.user
        self.object.project = self.get_object()
        self.object.save()
        return super().form_valid(form)

mysite/board/templates/board/authorisation.html
{% extends 'base.html' %}
{% block title %}Авторизация{% endblock title %}
{% block content %}
<div class="container d-flex justify-content-center ">
<h1 class ="mr-4">Авторизация</h1>
<div class ="col-4 ">
    <form id = "projectform" method="post">
          {% csrf_token %}
          {{ form }}
     <button form = "projectform" type="submit" class="btn btn-primary mt-4">Войти</button>
    </form>
</div>
    </div>
{% endblock content %}

mysite/board/templates/board/cabinet.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
{% if update %}
<div class="container d-flex justify-content-center ">
<h1>Обновление кабинета</h1>
{% if success_update %}
<p style="color:red">Кабинет обновлен</p>
{% endif %}
<br><br>
<form id = "update_data" method="post">
          {% csrf_token %}
          {{ form }}
</form>
</div>
<div class="container">
<button form = "update_data" type="submit" class="btn btn-primary">Обновить</button>
</div>
{% else %}
<div class="container">
  <nav class="text-left mt-4">
    <p>Логин пользователя: {{profile.username}}</p>
    <p>Имя и фамилия пользователя: {{profile.first_name}} {{profile.last_name}}</p>
    <p>Почта: {{profile.email}}</p>
    <p>Дата регистрации: {{profile.date_joined}}</p>
</nav>
  <a class="btn btn-primary" href="{% url 'board:updatecabinet' pk=request.user.id %}" role="button">Редактировать профиль</a><br><br>
</div>
{% endif %}
{% endblock content %}

mysite/board/templates/board/detail.html
{% extends 'base.html' %}
{% block title %}Компания {{company.name}}{% endblock title %}
{% block content %}
{% if update %}
<div class="container">
<div class="d-flex justify-content-center ">
  <h1>Обновление данных</h1>
  {% if success_update %}
    <p style="color:red">Данные обновлены</p>
  {% endif %}
  <br><br>
  <form id = "update_data" method="post">
            {% csrf_token %}
            {{ form }}
  </form>
</div>
<button form = "update_data" type="submit" class="btn btn-primary">Обновить</button>
</div>
{% else %}
<div class="container ">
  <h2>{{company.name}}:</h2>
  <div class="row">
    <div class="col-sm">
  <nav class="text-left mt-4">
    <p>Директор: {{company.fio}}</p>
    <p>Описание компании: {{company.content}}</p>
    <p>Опубликовано: {{company.published|date:"d.m.Y H:i:s" }}</p>
    <p>Выполнено: {{company.done|date:"d.m.Y H:i:s" }}</p>
    <p>Адрес компании: {{company.adress}}</p>
    <p>Телефон компании: {{company.phone}}</p>
    <p>Email: {{company.email}}</p>
  </nav>
    </div>
    <div class="col-sm">
  <nav class="text-right mt-4 ">
    <a class="btn btn-primary" href="{% url 'board:updatecompany' pk=company.pk %}" role="button">Редактировать компанию</a><br><br>
<form id="delete_form" action="{% url 'board:deletecompany' pk=company.pk %}" method="post">{% csrf_token %}</form>
        <a class="btn btn-primary" href="javascript:void()" onclick="delete_question()">Удалить</a>
        <script>
          function delete_question(){
            if (confirm("Удалить компанию?")){
                document.getElementById('delete_form').submit()
            }
          }
        </script>
    <br>
<button type="button" class="btn btn-primary mt-4 ml-4" data-toggle="modal" data-target="#exampleModal">
  Добавить проект
</button>
<button type="button" class="btn btn-primary mt-4 ml-4" data-toggle="modal" data-target="#commentModal">
  Добавить комментарий
</button>
  </nav>
    </div>
  </div>
</div>
<br><br>
{% if current_project %}
<div class="container ">
<h2>Проекты:</h2>
<div class="mt-4 d-flex justify-content-center ">
<table class="table text-center">
  <thead>
    <tr>
      <th scope="col">Название компании</th>
      <th scope="col">Название проекта</th>
      <th scope="col">Описание проекта</th>
      <th scope="col">Дата1</th>
      <th scope="col">Дата2</th>
      <th scope="col">Цена</th>
      <th scope="col">Редактировать</th>
      <th scope="col">Удалить</th>
    </tr>
  </thead>
  <tbody>
  {% for i in current_project %}
    <tr>
      <td>{{i.company}}</td>
      <td><a href="{% url 'board:detailproject' pk=i.id %}">{{i.title}}</a></td>
      <td>{{i.content| safe}}</td>
      <td>{{i.date1}}</td>
      <td>{{i.date2}}</td>
      <td>{{i.price}}</td>
      <td><a href="{% url 'board:updateproject' pk=i.id %}">Редактировать</a></td>
      <td><a href="{% url 'board:deleteproject' pk=i.id %}">Удалить</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
  <div class="container mt-4 d-flex justify-content-center ">
  <h4>Проекты не найдены</h4>
  </div>
{% endif %}
</div>
</div>

<br><br>

<div class="container">
   <ul class = "list-group mt-2">
     {% if current_comment %}
  <h2>Комментарии:</h2>
  {% for i in current_comment %}
            <li class = "list-group-item">

                <span class ="ml-3">Менеджер: {{i.manager}}</span>

                <span class ="ml-3">Канал общения: {{i.chanel}}</span>
                <span class ="ml-3">Оценка: {{i.ergebnis}}</span><br>
                <span class ="ml-3">Текст комментария: {{i.text}}</span>
                <p class ="ml-3">Автор: {{i.author}}</p>
            </li>
     <br>
        </ul>
  {% endfor %}
  {% else %}
  <div class="container mt-4 d-flex justify-content-center ">
  <h4>Комментарии не найдены</h4>
  </div>
  {%endif%}
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Добавление проекта</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id = "projectform" method="post">
          {% csrf_token %}
          {{ form.as_p }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
        <button form = "projectform" name="form" type="submit" class="btn btn-primary">Добавить</button>
      </div>
    </div>
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="commentModalLabel">Добавление комментария</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id = "commentform" method="post">
          {% csrf_token %}
          {{ form2.as_p }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
        <button form = "commentform" name="form2" type="submit" class="btn btn-primary">Добавить</button>
      </div>
    </div>
  </div>
</div>
{% endif %}

{% endblock content %}

mysite/board/templates/board/detailproject.html
{% extends 'base.html' %}
{% block title %}Проект {{project.title}}{% endblock title %}
{% block content %}
{% if update %}
<div class="container">
<div class="d-flex justify-content-center ">
  <h1>Обновление данных</h1>
  {% if success_update %}
    <p style="color:red">Данные обновлены</p>
  {% endif %}
  <br><br>
  <form id = "update_data" method="post">
            {% csrf_token %}
            {{ form }}
  </form>
</div>
<button form = "update_data" type="submit" class="btn btn-primary">Обновить</button>
</div>
{% else %}
<div class="container ">
  <h2>Проект: {{project.title}}</h2>
  <div class="row">
    <div class="col-sm">
  <nav class="text-left mt-4">
    <p>Компания: {{project.company}}</p>
    <p>Описание проекта: {{project.content }}</p>
    <p>Дата начала: {{project.date1 }}</p>
    <p>Дата завершения: {{project.date2}}</p>
    <p>Цена: {{project.price}}</p>
    <p>Автор: {{project.author}}</p>
  </nav>
    </div>
    <div class="col-sm">
  <nav class="text-right mt-4 ">
    <a class="btn btn-primary" href="{% url 'board:updateproject' pk=project.id %}" role="button">Редактировать</a><br><br>
    <a class="btn btn-primary" href="{% url 'board:deleteproject' pk=project.id %}" role="button">Удалить</a><br><br>
<button type="button" class="btn btn-primary ml-4" data-toggle="modal" data-target="#exampleModal">
  Добавить комментарий
</button>
  </nav>
    </div>
  </div>
</div>
<div class="container">
   <ul class = "list-group mt-2">
     {% if current_comment %}
  <h2>Комментарии:</h2>
  {% for i in current_comment %}
            <li class = "list-group-item">

                <span class ="ml-3">Менеджер: {{i.manager}}</span>

                <span class ="ml-3">Канал общения: {{i.chanel}}</span>
                <span class ="ml-3">Оценка: {{i.ergebnis}}</span><br>
                <span class ="ml-3">Текст комментария: {{i.text}}</span>
                <p class ="ml-3">Автор: {{i.author}}</p>
                <a class ="ml-3" href="{% url 'board:updatecomment' pk=i.id %}" >Редактировать</a>
                <a  class ="ml-3" href="{% url 'board:deletecomment' pk=i.id %}" >Удалить</a>
            </li>
     <br>
        </ul>
  {% endfor %}
  {% endif %}
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Добавление комментария</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id = "add_form" method="post">
          {% csrf_token %}
          {{ form }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
        <button form = "add_form" type="submit" class="btn btn-primary">Добавить</button>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock content %}

mysite/board/templates/board/register.html
{% extends 'base.html' %}
{% block title %}Авторизация{% endblock title %}
{% block content %}
<div class="container d-flex justify-content-center ">
<h1 class =" mr-4">Регистрация</h1>
</div>
<div class="container col-4">
<form id = "projectform" method="post">
          {% csrf_token %}
          {{ form }}
    <div class="container d-flex justify-content-center ">
    <button form = "projectform" type="submit" class="btn btn-primary mt-4">Зарегистрироваться</button>
    </div>
        </form>


    </div>


{% endblock content %}